services:
  app:
    image: git-cache-server
    build: .
    ports:
    - 8080:80
    - 9000:9000
    - 9418:9418
    environment:
      S6_KEEP_ENV: '1'
    volumes:    
    - git-cache:/srv/git
volumes:
  git-cache: {}
