services:
  git:
    enabled: true
  http:
    enabled: true
  api:
    enabled: true
  cron:
    enabled: true
repos:
- name: git-cache-server
  url: https://github.com/rophy/git-cache-server.git
  branch: main
  cron: "* * * * *"
gitConfigs:
- key: user.name
  value: bob
- key: user.email
  value: bob@example.com
